# Generated by Django 3.2.7 on 2021-09-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('skills', models.TextField(verbose_name='Skills')),
                ('calendly', models.URLField(verbose_name='Calendly Link')),
            ],
        ),
    ]
