# Generated by Django 3.2.7 on 2021-09-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
    ]
