# Generated by Django 3.2.7 on 2021-09-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('skills', models.TextField(verbose_name='Skills')),
                ('description', models.TextField(verbose_name='Description')),
                ('experience', models.TextField(verbose_name='Experience')),
            ],
        ),
    ]
