# Generated by Django 3.2.7 on 2021-09-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='calendly',
            field=models.URLField(default='', verbose_name='Calendly'),
        ),
    ]
